spring:
  application:
    name: DocumentSearch-service

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}            # OpenAI API 키 (환경 변수로부터)
      embedding:
        api-key: ${OPENAI_API_KEY}
        options:
          model: text-embedding-ada-002

    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY}           # Pinecone API 키
        index-name: ${PINECONE_INDEX}          # Pinecone 인덱스 이름
        environment: ${PINECONE_ENVIRONMENT}
        endpoint: https://dongmunseodap-document-index-dev-1a3x1qg.svc.aped-4627-b74a.pinecone.io

  server:
    port: 8081
    servlet:
      context-path: /
      encoding:
        enabled: true
        force: true
        charset: UTF-8
    error:
      include-message: always
      include-exception: true

logging:
  level:
    org.springframework.ai: DEBUG




